### ISSUE TITLE
Do you have plan for Python implementation 

### ISSUE THREAD

**Issue by YubinXie** [nolanlab/REDSEA#2]
Thanks for developing this signal correction method. It is definitely essential for multiplexed imaging analysis. 

I noticed that the code currently is only in MATLAB and I was wondering if there is a plan for Python implementation. Many thanks!

**Comment by BokaiZhu** [comment]
Hi Yubin, thanks for the comment! We do have plans to implement a python version of REDSEA. We have written a preliminary python script earlier and will update it once fully finished.

**Comment by YubinXie** [comment]
Very cool! That's awesome! Thanks Bokai!

**Comment by jacob-rosenthal** [comment]
Hi @BokaiZhu, thanks so much for making this repo public!!! Any plans to release a python implementation soon?

**Comment by BokaiZhu** [comment]
Hi everyone,

Thanks for the follow-up on this issue, I finally uploaded the python code onto this repo (```code/REDSEApy/```). It is a direct translation from the MATLAB code, and it should perform exactly the same (while some helper functions and pre-filtering steps are not in there). It contains a Jupiter notebook containing well-annotated code (hopefully). To be noted this is something that is not extensively tested so please report if anything is not working as it should be in the MATLAB code.   

Best,
Bokai

**Comment by jacob-rosenthal** [comment]
Incredible! Thanks for such a quick response!! Really appreciate it
