### ISSUE TITLE
Introduction of NaN when cells don't border other cells

### ISSUE THREAD

**Issue by nilseling** [nolanlab/REDSEA#3]
Hi,
first: thanks for releasing the code here!
I have tested the scripts on our data and found a potential issue when individual cells are not directly neighbouring other cells. As far as I understand, [here](https://github.com/nolanlab/REDSEA/blob/8c23798f9675548874eb2207f1bf9963024833ae/code/Lib/MIBIboundary_compensation_wholeCellSA.m#L52) you calculate the total boundary as the sum of boundaries to neighbouring cells. In cases where cells are not in direct contact with other cells, the sum is 0. Next, [here](https://github.com/nolanlab/REDSEA/blob/8c23798f9675548874eb2207f1bf9963024833ae/code/Lib/MIBIboundary_compensation_wholeCellSA.m#L56) boundary length is divided by 0, introducing `NaN` which propagates to the summation [here](https://github.com/nolanlab/REDSEA/blob/8c23798f9675548874eb2207f1bf9963024833ae/code/Lib/MIBIboundary_compensation_wholeCellSA.m#L63) filling the normalized data matrix with `NaN`.  One fix might be to set `cellPairNorm(isnan(cellPairNorm)) = 0;` after line 56. I hope I didn't miss anything.
Thanks! 
Nils

**Comment by yunhaoBai** [comment]
Hi Nils,

Thanks for using the code and your feedback!

This is highly likely a segmentation mask formatting issue, we actually noticed that issue when we was trying to adapt the REDSEA to other segmentation masks.

So the idea here is that our segmentation mask does not really has vacant region, the regions without cells was also labeled with numbers and their boundaries to real cells can also be recognized and summed, so no NaN will be generated. But those "cells" will be removed by the "labelIdentityNew2" parameter in downstream analysis.

I guess in your case, the large non-cell regions will just be labeled the same as the boundaries, am I correct?

Best wishes!

Yunhao

**Comment by nilseling** [comment]
Hey Yunhao,

thanks for the explanation! I was already wondering where these filtering steps are coming from. You are right that in my masks the background is labelled `0`. Do you have a recommendation on how to adapt the scripts to account for the missing labels in between cells? I'd prefer to not label empty regions with non-0 IDs as it might cause confusion in downstream analyses. 
Best,

Nils

**Comment by yunhaoBai** [comment]
Hi Nils,

Still depends on what is the formatting of your segmentation: I think likely it will be each cell has a unique number, no boundary labels and background is labeled as `0` (while in REDSEA the segmentation was like: cells will be divided by a 1-pixel line with all `0`, and the vacant regions are also recoginized as "cells" but will be removed later).

If the segmentation formatting is what I just guessed, we definitely have tackled this issue a bit, but I am sorry that I do not have a releasable version of the code right away. The simplest way will be change L39 [https://github.com/nolanlab/REDSEA/blob/8c23798f9675548874eb2207f1bf9963024833ae/code/Lib/MIBIboundary_compensation_wholeCellSA.m#L39](url) from ">=3" to ">=2" (also need to do some minor changes for double-counting, etc), also remove L31 [https://github.com/nolanlab/REDSEA/blob/8c23798f9675548874eb2207f1bf9963024833ae/code/Lib/MIBIboundary_compensation_wholeCellSA.m#L31](url) to loop through every pixels, in this case, you need to be particularly careful about the compensation to all the `0` regions as that is normally one or multiple large and may not interconnect regions and compensation with them is misleading. (and of course, I will recommend to first make a mask of Boundary pixels of each cells to replace L31 [https://github.com/nolanlab/REDSEA/blob/8c23798f9675548874eb2207f1bf9963024833ae/code/Lib/MIBIboundary_compensation_wholeCellSA.m#L31](url) to accelerate)

Best wishes!

Yunhao

**Comment by nilseling** [comment]
Hey Yunhao,

thanks for the input. I'll play around with this and see how far I get. And yes, it's the segmentation mask formatting as you described that causes the issue. For most segmentation masks all background pixels are labelled as `0`, not distinguishing between vacant regions and boundary. So I guess it would be quite nice to support these masks. Or otherwise provide a script that fills vacant regions with IDs > max(cellID). Feel free to close the issue. And again thanks for addressing this.
Best,

Nils
