### ISSUE TITLE
Masks & multichannel transform

### ISSUE THREAD

**Issue by YZYwoazzzzz** [nolanlab/REDSEA#4]
Hi, Bokai
Would you mind share some scripts for generating segmentationParams.mat file from a masks  tiff file and multichannel tiff to single channel tiff ? Make it easier to using downsteam boundary compensation. 
Thx.

**Comment by BokaiZhu** [comment]
Hi Sorry for the late reply, just saw this issue, not sure if you still need it but here is my answer:

1. the script to produce segmentationParams.mat is presented in the tutorial, with the script " MibiSegmentByDeepProbWithPerim3.m". Hope this can help you have a better idea of how the mat file is created.
2. For the multichannel tiff to single-channel tiff task we don't have a specific script for that but should be relatively straightforward to do in ImageJ or python. Without a detailed format of your tiff files, we can not provide a generalized solution for this task.

Thanks!
