### ISSUE TITLE
.fcs output

### ISSUE THREAD

**Issue by StiThor** [nolanlab/REDSEA#5]
Hi,

Super cool that you guys have developed this algorithm for spillover correction of signals for this type of data. Trying to run the Jupyter script, and it seems to be working fine. But I would like to get the output as .fcs files for downstream analysis. How can I do that?

**Comment by BokaiZhu** [comment]
Hi StiThor,

Thanks for trying out the method. You should be able to convert the output into .fcs files using some external python packages. For example [this](https://github.com/DC-analysis/fcswrite/blob/master/examples/numpy2fcs.py) might be something you could try, which it is converting a numpy matrix into fcs files, so you could do pandas dataframe we outputted -> numpy matrix -> fcs file. I'm sure there are more ways to convert but let me know if you can't find the function that best fits your need.
