### ISSUE TITLE
Running matlab with example data

### ISSUE THREAD

**Issue by StiThor** [nolanlab/REDSEA#6]
Hi,

Why do I get an error with "rgb_image = MibiGetRGBimageFromMat(nucLm,maxv)" running the script in MATLAB?
![MATLAB](https://user-images.githubusercontent.com/90035897/198207188-7af32dd7-87fa-4adc-a675-718db68f1e36.png)

**Comment by yunhaoBai** [comment]
Hi Stian,
Please include folder "Lib" in the leftside window by right click that folder -> Add to Path -> Selected Folders and Subfolders

Best,
Yunhao

**Comment by StiThor** [comment]
Thanks! The problem was solved, while another occurred.
![MATLAB](https://user-images.githubusercontent.com/90035897/198224154-e7115f38-7df1-4596-9b9f-c8a9a5cb268d.png)

**Comment by yunhaoBai** [comment]
Hi Stian,
Please check the document for this function (https://www.mathworks.com/help/images/ref/imextendedmax.html), I saw no reason it cannot process with double datatype, 
but if it reported something like this, please double check that your MatLab has Image Processing Toolbox.

Best,
Yunhao

**Comment by StiThor** [comment]
Thanks so much! Its working :)
