### ISSUE TITLE
No License in Repo

### ISSUE THREAD

**Issue by BenCaiello** [nolanlab/REDSEA#8]
Hello yunhaoBai and BokaiZhu!
There is no license in the repository and was wondering if that was an oversight -- technically no license means that no one can legally use / modify the code here -- although that seems directly contrary to your intentions and your communications here about RedSEA.
As I'd talked with you in a separate issue, I've been making (and now have made) a python script for integrating this algorithm with steinbock in a separate fork of RedSEA, but I'm happy to take it down if you don't want versions of your repo being made.

**Comment by BokaiZhu** [comment]
Thanks! Added an academic license to this repo, meaning it would remain to be freely accessible as long as for research purposes.

**Comment by BenCaiello** [comment]
OK! I see it now. It looks like Stanford has quite a restrictive academic license (no modifications allowed, oops).

Do you want me to open a pull request so that you can optionally merge my fork and make it "official" and easier to access? The only change should be the addition of my experimental steinbock-integrated jupyter notebook script, everything is untouched.

**Comment by BokaiZhu** [comment]
ooops I'm not a legal expert but let's presume no modification happened yet, it would just be an extension in our case? If eventually it would be a problem I'm happy to consult the school and get a less restrictive license.

For pull request feel free to do so!

**Comment by BenCaiello** [comment]
I'm quite confident that my script would certainly fall under the category of a modification of the software, but you as author should be able to make changes -- license restrictions only restrict the rights of recipients of a software, not the rights of the authors -- although I guess if you are not at Stanford anymore maybe that becomes a bit of a grey area. 

I'll open the pull request and you can take a look!

**Comment by BokaiZhu** [comment]
Confirmed the pull request and added some info in the pyscript folder.

For the license, I will also consult this matter with Stanford. But from our initial intention of this project, please feel free to do your own modification etc (and post here if you want), as long as it is for research.
